// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfScmTTYgX_mvIoFZBsUVlHQs8TVwoJX0',
    appId: '1:604409398138:web:cf3066ba83d1cca926ccc3',
    messagingSenderId: '604409398138',
    projectId: 'bite-food-delivery-8920e',
    authDomain: 'bite-food-delivery-8920e.firebaseapp.com',
    storageBucket: 'bite-food-delivery-8920e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC82kPBtaeOP2x7plWGn7BaJ45vPQ424ds',
    appId: '1:604409398138:android:34b4b9029be8f02226ccc3',
    messagingSenderId: '604409398138',
    projectId: 'bite-food-delivery-8920e',
    storageBucket: 'bite-food-delivery-8920e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4rm7q1umpCLRlOeYq7WJRSZf95aG-oP8',
    appId: '1:604409398138:ios:95d60c9d022e2d4626ccc3',
    messagingSenderId: '604409398138',
    projectId: 'bite-food-delivery-8920e',
    storageBucket: 'bite-food-delivery-8920e.firebasestorage.app',
    iosClientId: '604409398138-hdl5hn5phv23o3p3g3u8vdgset3h509u.apps.googleusercontent.com',
    iosBundleId: 'com.example.biteFoodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4rm7q1umpCLRlOeYq7WJRSZf95aG-oP8',
    appId: '1:604409398138:ios:95d60c9d022e2d4626ccc3',
    messagingSenderId: '604409398138',
    projectId: 'bite-food-delivery-8920e',
    storageBucket: 'bite-food-delivery-8920e.firebasestorage.app',
    iosClientId: '604409398138-hdl5hn5phv23o3p3g3u8vdgset3h509u.apps.googleusercontent.com',
    iosBundleId: 'com.example.biteFoodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfScmTTYgX_mvIoFZBsUVlHQs8TVwoJX0',
    appId: '1:604409398138:web:84c3c2a59d8abe7226ccc3',
    messagingSenderId: '604409398138',
    projectId: 'bite-food-delivery-8920e',
    authDomain: 'bite-food-delivery-8920e.firebaseapp.com',
    storageBucket: 'bite-food-delivery-8920e.firebasestorage.app',
  );
}
